# Generated by Django 5.2.6 on 2026-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('admin', 'Admin')], max_length=10),
        ),
    ]
