# Generated by Django 5.2.6 on 2026-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkify', '0004_ownerprofile_ownerdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='address',
            field=models.TextField(),
        ),
    ]
