# Generated by Django 5.2.6 on 2026-06-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkify', '0005_remove_ownerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('car_capacity', models.IntegerField()),
                ('bike_capacity', models.IntegerField()),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkify.ownerprofile')),
            ],
        ),
    ]
