# Generated by Django 5.2.6 on 2026-06-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkify', '0006_parkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='parking_image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_images/'),
        ),
    ]
