# Generated by Django 5.2.6 on 2026-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkify', '0007_parkinglot_parking_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
