# Generated by Django 5.2.6 on 2026-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkify', '0009_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
