# Generated by Django 5.2.6 on 2026-07-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkify', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
