# Generated by Django 5.2.6 on 2026-07-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parkify", "0015_signup_is_active_signup_two_factor_enabled_otpcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login 2FA"),
                    ("reactivation", "Account Reactivation"),
                ],
                default="login",
                max_length=20,
            ),
        ),
    ]
