"""
Django settings for parkify_main project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY as an environment variable in Railway. The hardcoded value
# is kept only as a local-dev fallback so `runserver` still works without a
# .env file.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-f7q*w$lazcrx=&$z2t=ual^iakzp8_3un-6t2hut)!%7=5!gnq',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe for Railway). Set DEBUG=True in your local .env
# for development.
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Railway sets RAILWAY_PUBLIC_DOMAIN for the service's public domain.
# ALLOWED_HOSTS can also be overridden with a comma-separated ALLOWED_HOSTS
# env var if you attach a custom domain.
ALLOWED_HOSTS = ['*']
_env_allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if _env_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _env_allowed_hosts.split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    'https://*.up.railway.app',
]
_railway_public_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_public_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_public_domain}')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# The authentication page embeds the homepage in an <iframe> (blurred, as a
# backdrop behind the login/signup modal). Django blocks framing by default
# (X-Frame-Options: DENY) - SAMEORIGIN allows this same-site embed while still
# blocking any other site from framing us.
X_FRAME_OPTIONS = 'SAMEORIGIN'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parkify',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ---------------------------------------------------------------------------
# Google Sign-In (django-allauth)
# ---------------------------------------------------------------------------
# Parkify has its own `Signup` model + session-based login instead of
# django.contrib.auth's User model, so allauth's normal "create a User"
# behaviour is intercepted by parkify/adapters.py::ParkifySocialAccountAdapter,
# which finds-or-creates the matching Signup row and logs the person in the
# same way the username/password form does. See that file for details.
SOCIALACCOUNT_ADAPTER = 'parkify.adapters.ParkifySocialAccountAdapter'

# Lets the "Continue with Google" link be a plain <a href>, GET request
# (instead of requiring a CSRF-protected POST form).
SOCIALACCOUNT_LOGIN_ON_GET = True

# Set these two as real environment variables in production. For local
# development you can either export them before running the server, or
# temporarily hardcode them here (never commit real secrets).
#   GOOGLE_CLIENT_ID=xxxxxxxx.apps.googleusercontent.com
#   GOOGLE_CLIENT_SECRET=xxxxxxxx
# Get them from https://console.cloud.google.com/apis/credentials
# Authorized redirect URI to whitelist there:
#   http://127.0.0.1:8000/accounts/google/login/callback/   (local dev)
#   https://<your-domain>/accounts/google/login/callback/   (production)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# Email backend for password reset (console for dev/testing)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGIN_REDIRECT_URL = '/dashboard/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parkify_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parkify_main.wsgi.application'


# Database



# Railway injects a DATABASE_URL for whichever database plugin (Postgres or
# MySQL) you attach to this service. dj_database_url parses it into Django's
# DATABASES format. Locally, falls back to the same MySQL setup this project
# used to hardcode - override any of it via a .env file if your local setup
# differs.
_local_default_db_url = 'mysql://root:Meroshare%401804@localhost:3306/parkify_db'

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', _local_default_db_url),
        conn_max_age=600,
        ssl_require=os.environ.get('DATABASE_SSL_REQUIRE', 'False').lower() == 'true',
    )
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serves static files directly from gunicorn with far-future
# cache headers + compression, so no separate CDN/nginx is needed on Railway.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'